---
- name: Install Docker
  become: true
  ansible.builtin.yum:
    name: docker
    state: present

- name: Enable and start service 'docker'
  become: true
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true
